# Generated by Django 2.0.7 on 2019-02-20 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tempSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowerBound', models.IntegerField()),
                ('upperBound', models.IntegerField()),
                ('currentTemp', models.IntegerField()),
                ('timeChanged', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
